<a href="https://colab.research.google.com/github/sh1vam31/DataScience_Sheryians/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Using NumPy**

Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [4]:
a = [1,2,3,4,5] # Its is just a normal list
b = ["1",2,3,4,5]  # saare element ka datatype change kar deta hai
arr = np.array(a)   # converting the list to a numpy array using -> np.array()
arr1 = np.array(b)
print(arr)
print(arr1)

[1 2 3 4 5]
['1' '2' '3' '4' '5']


Lets create a matrix using list

In [ ]:
a = [[1,2,3],[4,5,6],[7,8,9]]
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Now lets see how matlix looks like using numpy arrays

In [ ]:
arr = np.array(a)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
np.zeros([3,4]) #row and columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.full(5,7)

array([7, 7, 7, 7, 7])

In [ ]:
np.full([5,5],7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [ ]:
# arange use for arranging an array
arr = np.arange(0, 10, 2)   # start=0, stop=10, step=2
print(arr)

[0 2 4 6 8]


In [ ]:
# linspace -> create an array between value 0 to 1 and usme 5 values honi chaiye orr 5 values ke bech mai same difference (linespace) ho.
arr = np.linspace(0, 1, 5)   # start=0, stop=1, 5 values
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# eye -> 4x4 identity matrix
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# random.rand -> give a random number between 0 to 1
arr = np.random.rand(2, 3)   # 2x3 array
print(arr)

[[0.57977045 0.04165422 0.45822095]
 [0.77345437 0.23146486 0.73424197]]


In [6]:
# random.randint -> give a random number between your provided range (1 to 10 , size(3, 3))
arr = np.random.randint(1, 10, [3, 3])   # 3x3 integers from 1–9
print(arr)

[[8 2 8]
 [4 7 2]
 [8 8 4]]


In [ ]:
# random.randn(size) -> give you a random number between -3 to +3
arr = np.random.randn(2, 4)   # 2x4 array
print(arr)

[[ 0.07347377  0.00554962 -1.47463013 -0.45858195]
 [-0.41830681  0.86342212  0.64891109 -0.83237775]]


arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution